services:
  - type: web
    name: finopoly
    env: node
    plan: free
    buildCommand: "cd market-masters && npm install && cd client && npm install && npm run build"
    startCommand: "cd market-masters/server && npm install && node index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
